name: 微客众智

on:
  workflow_dispatch:
  schedule:
     - cron: '7 16,19,22,1,4,7-13 * * *'
  watch:
    types: wkzz
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        WKZZ_HD: ${{ secrets.WKZZ_HD }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: 安装依赖项
        run: |
          npm install
      - name: '运行 【微客众智】'
        if: env.WKZZ_HD
        run: |
          node Task/wkzz.js
