name: 微客众智

on:
  workflow_dispatch:
  schedule:
     - cron: '7 16,19,22,1,4,7-13 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
         WKZZ_HD: ${{ secrets.WKZZ_HD }}
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/Lxg2/Scripts.git ~/Scripts
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          cd ~/Scripts
          npm install
      - name: '运行 【微客众智】'     
        run: |
          cd ~/Scripts
          node Task/wkzz.js
