name: 葱花自动刷视频

on:
  workflow_dispatch:
  schedule:
     - cron: '0 0,3,6,9 * * *'
  watch:
    types: started
jobs:
  build:
    env:
      RONGHUA_VIDEO: ${{ secrets.RONGHUA_VIDEO }}
      RONGHUA_VIDEO2: ${{ secrets.RONGHUA_VIDEO2 }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【葱花视频账号1-视频阅读】'
        if: env.RONGHUA_VIDEO
        run: |
          node RONGHUA_VIDEO.js
        env:
          RONGHUA_VIDEO: ${{ secrets.RONGHUA_VIDEO }}

      - name: '运行 【葱花视频账号1-视频阅读2】'
        if: env.RONGHUA_VIDEO2
        run: |
          node RONGHUA_VIDEO.js
        env:
          RONGHUA_VIDEO: ${{ secrets.RONGHUA_VIDEO2 }}
